[package]
name = "chat"
version = "0.1.0"
authors = ["Nao Minami <south37777@gmail.com>"]

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dependencies]
http-muncher = "0.2.1"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
